image: node:lts
before_script:
  - npm i -g envinfo && envinfo

cache:
  paths:
    - node_modules/

stages:
  - build

build@node-lts:
  stage: build
  script:
    - npm i
    - npm run build
  # https://docs.gitlab.com/ee/ci/yaml/README.html#artifacts
  artifacts:
    paths:
      - dist/
    expire_in: 2 weeks
  tags:
    - docker

build@node8:
  image: node:8
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 2 weeks
  tags:
    - docker

build@node6:
  image: node:6
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 2 weeks
  tags:
    - docker
